spring:

  .main:
    banner-mode: off

#  .h2.console:
#    enabled: true
#    path: '/console'
#
#  .jpa:
#    #    generate-ddl: true
#    show-sql: true
#    hibernate.ddl-auto: validate
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  .datasource:
#    url: 'jdbc:h2:C:/Users/Public/loginDB'
#    username: 'sa'
